name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.17
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ^10.0.1
  collection: ^1.19.1
  gherkin:
    git:
      # FIXME This dependency must be removed after the merge of this PR: https://github.com/jonsamwell/dart_gherkin/pull/71
      url: https://github.com/BL-CARL/dart_gherkin.git
      ref: c335169f04e3d14c1f104a65a47ce0f3b02a911d
  source_gen: ^4.2.0
  build: ^4.0.4
  glob: ^2.1.3

dev_dependencies:
  meta: any
  build_config: ^1.3.0
  flutter_lints: ^6.0.0

flutter:
